### ISSUE TITLE
not possible to compile

### ISSUE THREAD

**Issue by mars3142** [LetsMakeAnIndieGame/PhysicsShmup#1]
This project is not compileable. I tested it with "gradlew run", but it can't start. It would be nice to get the actual code, because learning on not functional code is hard/impossible.

PS: I like your YT channel.

**Comment by LetsMakeAnIndieGame** [comment]
Hey.  I've had to take an indefinite break.  I don't even remember the last
time I worked on it, but my guess is that some update to LibGDX is causing
problems.  Within the next couple of months, I'll be able to get back into
the project and I'll probably update it.  Unfortunately, you'll have to
wait until then because I just don't have time.

**Comment by LetsMakeAnIndieGame** [comment]
I think I'm going to open this project up to pull requests.  Maybe that will get it fixed sooner.  I'll begin making additions to it again within the next couple of months, but no reason it has to wait that long.  Also, I need to split my time between this and other things so I don't plan on actually finishing the project necessarily.

**Comment by jarrodparkes** [comment]
Do you at least have a copy of "Levels/testlvl.tmx" and any other media files required to build/run the project? I've gotten the code to compile (by commenting out some of subStateMachine logic).

**Comment by LetsMakeAnIndieGame** [comment]
Hey, sorry it's taken me so long.  I've freed up some time, but I made a commitment to finish another project that slowed me down temporarily.  I'm going to take a look at the project today, update my build, and then try and run it.  If it works for me, then it's possible I screwed up the git repo and left out some necessary files.  I'll try to have it up and running by the end of today, and plan on having the next part in the series finished within the next two days at least, maybe a week tops.

**Comment by LetsMakeAnIndieGame** [comment]
Okay, I can't tell you why the gradlew run isn't working, because it works for me.  Or at least it did until I updated to the latest version of LibGDX which depricated a lot of code unfortunately, so now I need to do some minor rewrites before I can repost working code.  Also, strangely the latest versions of Ashley GDX-AI and Box2DLights were not working, so for now I'm going to leave them as is.  

Jarrod, if you're looking for Levels/testlvl.tmx it should be included in the repo.  I see it under: core/assets/Levels/testlvl.tmx

Anyway, check back later tonight for the updated git, and so long as I see it working I'm going to close the issue unless (mars) you can provide me with an error message or something to go on to figure out why it's not working for you.

**Comment by LetsMakeAnIndieGame** [comment]
All right, I'm going to close this issue.  If you are still having problems after pulling down the latest code, let me know and please give me details so I can try to help.
